# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('yazi', models.TextField()),
                ('yayin_tarihi', models.DateTimeField()),
            ],
        ),
    ]
