# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120, verbose_name='başlık')),
                ('yazi', models.TextField(verbose_name='içerik')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='yayınlanma tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-yayin_tarihi', 'id'],
            },
        ),
    ]
