# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
    ]
