# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='baslik',
            field=models.CharField(max_length=120, verbose_name='başlık'),
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='yayin_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yayınlanma tarihi'),
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='yazi',
            field=models.TextField(verbose_name='içerik'),
        ),
    ]
