# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 13:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0002_auto_20190711_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='yazi',
            field=ckeditor.fields.RichTextField(verbose_name='içerik'),
        ),
    ]
