# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gonderi', '0003_auto_20190711_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='kullanici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
            preserve_default=False,
        ),
    ]
