# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0003_gonderi_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gonderi',
            options={'ordering': ['-yayin_tarihi', 'id']},
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
