# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0004_gonderi_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='isim')),
                ('yazi', models.TextField()),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderis', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='yorum',
            name='gonderi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='gonderi.Gonderi'),
        ),
    ]
