# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0005_auto_20190711_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='yazi',
            field=models.TextField(verbose_name='Yorum'),
        ),
    ]
